// Auto-generated by scripts/sync-flowr-sdk-local.mjs — do not edit.
export const playgroundSdkEntryUrl =
  "/vendor/flowr/sdk-recorder-local/index.js?v=2a0f59a53008";
export const playgroundSdkEntrySha256 = "2a0f59a53008c08c6e198462c463c67127144991ca05992631c606e9ebdd85a9";
