// Auto-generated by scripts/sync-flowr-sdk-local.mjs — do not edit.
export const playgroundSdkEntryUrl =
  "/vendor/flowr/sdk-recorder-local/index.js?v=0109b2a938a8";
export const playgroundSdkEntrySha256 = "0109b2a938a846d4ff9163155f1e796959ca89aaa673997665f0c45f8b7747b3";
